import React from 'react';
import { FaRobot, FaInfoCircle } from 'react-icons/fa';
import { motion } from 'framer-motion';

const AiSummary = ({ explanation, riskLevel }) => {
  if (!explanation) return null;

  const getThemeColor = () => {
    switch (riskLevel?.toLowerCase()) {
      case 'malicious':
      case 'high':
        return 'cyber-red';
      case 'suspicious':
      case 'medium':
        return 'yellow-400';
      case 'low risk':
      case 'low':
        return 'cyber-green';
      default:
        return 'cyber-blue';
    }
  };

  const themeColor = getThemeColor();

  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={`glass border border-${themeColor}/20 rounded-3xl p-8 relative overflow-hidden`}
    >
      <div className="flex items-center gap-3 mb-6">
        <div className={`p-2 rounded-lg bg-${themeColor}/10 text-${themeColor}`}>
          <FaRobot className="text-2xl" />
        </div>
        <div>
          <h3 className={`text-xs font-bold text-${themeColor} uppercase tracking-[0.2em]`}>
            AI-Powered Intelligence Report
          </h3>
          <p className="text-[10px] text-gray-500 uppercase font-mono mt-1">Generated by CyberNet Gemini-1.5</p>
        </div>
      </div>

      <div className="prose prose-invert max-w-none">
        <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap font-sans bg-white/5 p-6 rounded-2xl border border-white/5 ai-explanation-content">
          {explanation}
        </div>
      </div>

      <div className={`mt-6 p-4 bg-${themeColor}/5 border-l-4 border-${themeColor} rounded-r-xl flex items-start gap-3`}>
        <FaInfoCircle className={`text-${themeColor} mt-1`} />
        <p className="text-white text-xs italic leading-snug">
          This analysis is generated by AI based on multiple intelligence signals. Always verify critical findings.
        </p>
      </div>
    </motion.div>
  );
};

export default AiSummary;
